### ISSUE TITLE
Choosing a certificate in Visual Studio with the MSIX app manifest

### ISSUE THREAD

**Issue by gradyal** [microsoft/devops-for-windows-apps#24]
I'm following along in the video, but I'm having trouble seeing an option in Visual Studio that the presenter in the video uses at the 28:00 mark in the video. I'm using Visual Studio Enterprise 2019 version 16.1.1 with .NET Framework 4.7.03190. My problem is when I open the appxmanifest display > click the Packaging tab > click Choose Certificate > Select a Certificate > I do not see the More choices selection option as seen in the video. I've been looking through documentation but cannot see how to enable this option. I'd like to be able to select a self-signed certificate. Please advise. 

Screen capture from video:
![image](https://user-images.githubusercontent.com/5721295/58358381-3d219e00-7e44-11e9-8208-ca38bbe7bf6e.png)

Screen capture from my Visual Studio:
![image](https://user-images.githubusercontent.com/5721295/58358403-5c203000-7e44-11e9-8897-2f23eceb286d.png)

**Comment by rido-min** [comment]
Hi @gradyal  sorry for the confusion, in the session I used an internal VS preview where the certificate management is being redesigned.

The *more choices* option is shown only when you have more than one Code Signing certificate in your CurrentUser\My certificate store.

If you want to create a new self signed certificate to sign MSIX packages you can use the next command:

```ps
 New-SelfSignedCertificate -Subject "CN=Joey, O=Ramones, L=Queens, S=NewYork, C=US" `
    -FriendlyName Joey `
    -Type CodeSigning `
    -KeyUsage DigitalSignature `
    -KeyLength 2048 `
    -KeyAlgorithm RSA `
    -HashAlgorithm SHA256 `
    -TextExtension @('2.5.29.37={text}1.3.6.1.5.5.7.3.3', '2.5.29.19={text}Subject Type:End Entity') `
    -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider" `
    -CertStoreLocation "Cert:\CurrentUser\My"
```

Then you should be able to select it from the certificate picker under the *More choices* option. 

/c @mirkomuggli

**Comment by gradyal** [comment]
Thank you @rido-min! I had generated a self-signed cert, but it was in LocalMachine. I ran your script above and now I see the more choices option.
